### ISSUE TITLE
Implement support for other ligature fonts

### ISSUE THREAD

**Issue by minad** [minad/hasklig-mode#1]
* Monoid: https://github.com/larsenwork/monoid
* FiraCode: https://github.com/tonsky/FiraCode
* Iosevka: https://github.com/be5invis/Iosevka

Maybe create additional packages or rename this package to e.g. ligature-mode?

**Comment by minad** [comment]
See https://github.com/ar1a/.doom.d/blob/master/%2Bsymbols.el and https://gist.github.com/mrkgnao/49c7480e1df42405a36b7ab09fe87f3d for iosevka

**Comment by minad** [comment]
for fira:
https://github.com/Profpatsch/blog/blob/master/posts/ligature-emulation-in-emacs/post.md#appendix-b-update-1-firacode-integration
https://github.com/tonsky/FiraCode/wiki/Emacs-instructions (obsolete)

**Comment by minad** [comment]
Both fira and iosevka need patched fonts since they don't include ligatures in the private area :/

**Comment by gagbo** [comment]
Just piggy-backing on this issue for 1 question (and one remark I guess)

I'm trying to add Hasklig support in doom-emacs https://github.com/hlissner/doom-emacs/pull/1523 and I wonder how you were able to find the correct order for the glyphs to replace ? Is there a file to see in https://github.com/i-tu/Hasklig repo ?

Also, you can check https://github.com/hlissner/doom-emacs/tree/develop/modules/ui/pretty-code for other symbol list (Iosevka, PragmataPro and Fira for the time being)
