### ISSUE TITLE
Disappearing characters

### ISSUE THREAD

**Issue by camelpunch** [minad/hasklig-mode#2]
Using hasklig-mode in emacs 25.2.2 on GNU/Linux, I get disappearing characters at the end of words next to symbols.

For example, this screenshot should show `Shell Line`, `findYaml` and `FilePath`:

![screenshot from 2018-12-02 20-38-49](https://user-images.githubusercontent.com/141733/49344673-9fa69800-f672-11e8-90ac-0de2222dab06.png)

The problem goes away if I turn off/on hasklig-mode.

**Comment by minad** [comment]
I can reproduce the issue on Emacs 25.2. On Emacs 26 there are no problems.

**Comment by camelpunch** [comment]
Perfect - thanks for putting this together!
