### ISSUE TITLE
Ligatures don't work in the middle of words (identifiers)

### ISSUE THREAD

**Issue by SwitchAxe** [minad/hasklig-mode#3]
# Emacs version
GNU Emacs 28.1
# Hasklig-mode version
Latest? i installed it today from MELPA
# Issue
Hasklig-mode won't apply ligatures to words, so for instance, if i do:
```scheme
(list->string '(#\a #\b #\c))
```
in some Scheme code, the `->` will not turn into an arrow.
# Expected behaviour
ligatures appear inside identifiers (or, more generally, words)

# Extra: Why is this important?
Scheme code relies __heavily__ on this arrow "operator" to mean "turn object X into Y" and it would really be awesome if such support was added to hasklig-mode.

**Comment by minad** [comment]
hasklig-mode intentionally touches freestanding symbols/identifiers only. Anyway, hasklig-mode is going to be deprecated in the near future. You should look into more general alternatives, e.g., https://github.com/mickeynp/ligature.el.
